name: wuchuheng_helper
description: wuchuheng's help library
version: 0.0.1
homepage: https://github.com/wuchuheng/helper_dart

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
